spring:
  config:
    import: optional:file:./.env[.properties]

  application:
    name: qnectdb

  datasource:
    url: jdbc:mysql://localhost:3306/qnectdb?useSSL=false&serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: root
    password: khj0728!@
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

server:
  port: 8080

logging:
  level:
    root: INFO
    com.qnectdk: DEBUG

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true